name: Data Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t rfm-pipeline .

      - name: Run Pipeline
        run: |
          docker run --rm -v ${{ github.workspace }}:/app rfm-pipeline python3 scripts/main_orchestrator.py
          ls -R data/

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-outputs
          path: |
            data/processed_data/
            data/features/
            data/clusters/
            data/analytics/
            logs/
